[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
renew_protocol = "fScJ66UUXwsb4ogdFgYSZfEG7piyhTi4z9gZZe931oh"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/renew_protocol"]

[scripts]
test = "cargo test --workspace"
